services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-rinha
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  api1: &api
    build: .
    hostname: api1
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_APPLICATION_NAME=luiz
      - SERVER_PORT=8080
      - INSTANCE_ID=APP-1
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "85MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_APPLICATION_NAME=luiz
      - SERVER_PORT=8080
      - INSTANCE_ID=APP-2

  redis:
    image: redis:latest
    container_name: redis-rinha
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "232MB"

networks:
  backend:
    driver: bridge